AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CIMAgenda-Lambda
Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 3

Resources:
  CIMAgendaStoreFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
