AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Boilerplate-Lambdas
Metadata:
  AWS::ServerlessRepo::Application:
    Name: Boilerplate-Lambdas
    Description: Lambdas para utilizar en AppSync
    Author: Miguel Meza
    SpdxLicenseId: Apache-2.0
    Labels: ['lambdas']
    HomePageUrl: https://github.com/CIMAgenda/Boilerplate-Lambdas
    SourceCodeUrl: https://github.com/CIMAgenda/Boilerplate-Lambdas

Parameters:
  TableParameterName:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: Required. The DynamoDB table.
    Default: 'Book'
  NodeEnvironment:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: Required. Stage.
    Default: 'development'

Globals:
  Function:
    Runtime: nodejs12.x
    MemorySize: 128
    Timeout: 5
    Environment:
      Variables:
        ENV: !Ref NodeEnvironment

Resources:
  CreateBook:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/book/
      Description: >-
        Description of the Function.
      Handler: book.createBook
      Environment:
        Variables:
          TABLE_NAME: !Ref TableParameterName
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableParameterName

  BookTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Ref TableParameterName
      AttributeDefinitions:
        - AttributeName: pkey
          AttributeType: S

        - AttributeName: skey
          AttributeType: S
      KeySchema:
        - AttributeName: pkey
          KeyType: HASH

        - AttributeName: skey
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
